### PR TITLE
Show rejected styles when dragging multiple files and multiple==false

### LINKED ISSUE #409: When multiple is set to false the rejectClassName is not shown when multiple files are dragged in.
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Set multiple to false and have a rejectClassName
2. Drag 2 files onto the dropzone

**What is the expected behavior?**
The reject class is added to the dropzone element.

### PR DESCRIPTION
**Pull request by plee-nm**
…dragged in multi mode false.

**What kind of change does this PR introduce?**

- [x] bugfix
- [ ] feature
- [ ] refactoring / style
- [ ] build / chore
- [ ] documentation

**Did you add tests for your changes?**

- [x] Yes, my code is well tested
- [ ] Not relevant

**If relevant, did you update the documentation?**

- [ ] Yes, I've updated the documentation
- [ ] Not relevant

**Summary**

**Does this PR introduce a breaking change?**
Yes!

**Other information**
Closes #409

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -79,11 +79,14 @@ class Dropzone extends React.Component {
       this.dragTargets.push(e.target);
     }
 
-    const allFilesAccepted = this.allFilesAccepted(getDataTransferItems(e, this.props.multiple));
+    // validate all files regardless if they are in multi file mode.
+    const files = getDataTransferItems(e, true);
```
Comment (okonet) [inline src/index.js]: 1. Shouldn't it be aligned with https://github.com/okonet/react-dropzone/pull/410/files#diff-1fdf421c05c1140f6d71444ea2b27638R133?
1. `true` is default argument, so you can skip it

File: src/index.js [hunk 2]
```diff
@@ -79,11 +79,14 @@ class Dropzone extends React.Component {
...
+    const allFilesAccepted = this.allFilesAccepted(files);
+    const isMultipleNotAllowed = this.props.multiple ? false : files.length > 1;
```
Comment (okonet) [inline src/index.js]: 1. Let's remove negation from the variable name please
1. This can be rewritten as `!this.props.multiple || files.length > 1`

File: src/index.js [hunk 3]
```diff
@@ -79,11 +79,14 @@ class Dropzone extends React.Component {
...
 
     this.setState({
       isDragActive: allFilesAccepted,
-      isDragReject: !allFilesAccepted
+      isDragReject: !allFilesAccepted || isMultipleNotAllowed
```
Comment (okonet) [inline src/index.js]: Can `allFilesAccepted` be set accordingly before so this code remains intact?

**Comment by okonet** [comment]
This seems to be a breaking change, right?

**Comment by plee-nm** [comment]
@okonet Yeah it is a breaking change.  What are your thoughts on adding the extra files on drag to the rejected files or all the files as rejected if it is multiple?  Not sure how everyone feels about this but I don't want to have the user experience of a drop of N number of files and it only picking one and saying it is valid.  

We can do this as breaking change or we can add another config like allowMultipleDrop and default it to true.  Setting it to false would show the error class on drag and show any extra files as rejected files.  Or we label it as a breaking change and bump the major version.  Thoughts?  I can submit a PR with these changes.

**Comment by plee-nm** [comment]
@okonet I would push for just making a breaking change, the code will be cleaner and I think the behavior is better for the end user.  Also the breaking change would only affect users using multiple=false and it can be easily documented in a change log.

**Comment by okonet** [comment]
I think it makes sense to make a major version bump. The change you're proposing makes it more logical.

**Comment by plee-nm** [comment]
Alright great I'll submit a pr with these changes.

File: src/index.js (hunk 3 above)
Comment (plee-nm) [inline src/index.js]: Not sure what this means exactly.  I just pushed a change so let me know if I need to update it.

File: src/index.js (hunk 2 above)
Comment (plee-nm) [inline src/index.js]: I removed the negation with the new changes.

**Comment by plee-nm** [comment]
I just pushed the changes needed to add extra files to rejected when multiple is set to false.  Please let me know what the process is for a major version bump.

File: src/index.js [hunk 4]
```diff
@@ -159,6 +158,11 @@ class Dropzone extends React.Component {
       }
     });
 
+    if (!multiple) {
+      // if not in multi mode add any extra accepted files to rejected.  This will allow end users to easily ignore a multi file drop in "single" mode.
+      rejectedFiles.push(...acceptedFiles.splice(1));
```
Comment (okonet) [inline src/index.js]: Can this be rewritten with array destructuring?

File: src/index.js [hunk 5]
```diff
@@ -159,6 +158,11 @@ class Dropzone extends React.Component {
       }
     });
 
+    if (!multiple) {
+      // if not in multi mode add any extra accepted files to rejected.  This will allow end users to easily ignore a multi file drop in "single" mode.
```
Comment (okonet) [inline src/index.js]: Please split the comment into 2 lines

File: src/index.spec.js [hunk 6]
```diff
@@ -455,44 +455,58 @@ describe('Dropzone', () => {
       expect(dropzone.state().isDragReject).toEqual(false);
     });
 
-    it('should expose acceptedFiles and rejectedFiles to children', () => {
+    it('multiple false valid files adds to rejected files on a multple drop', () => {
```
Comment (okonet) [inline src/index.spec.js]: Can we still keep `should`s in tests?

**Comment by okonet** [comment]
Don't worry about the version bump. I'll take care of this during the merge!

File: src/index.js (hunk 4 above)
Comment (plee-nm) [inline src/index.js]: Change acceptedFiles to a `let` so it can be redefined and then do something like 

```
const [accepted, ...rejected] = acceptedFiles;
rejectedFiles.push(...rejected);
acceptedFiles = [accepted];
```

Or just leave it as it is?

Comment (okonet) [inline src/index.js]: Let's leave as is. Thanks for clarifying.

**Comment by okonet** [comment]
Hey @plee-nm I've just added some more examples. Could you please check you branch out, run `npm start` and test all the examples if they still work? Since you can live-change the examples, try out different states.

**Comment by plee-nm** [comment]
@okonet Just ran through the all the examples, looks like everything is working.

**Comment by okonet** [comment]
I'm looking at how it works now and it doesn't seem to be any breaking changes. We'll still call `onDrop` with the single file. I think it can be released as patch. Am I missing something?

**Comment by plee-nm** [comment]
@okonet it is kind of a gray area because it is fixing undefined behavior.  Making it a major would make sure no one that is relying on the undefined behavior is broken.   Patch or Major I would have some kind of release note saying:  when multiple=false on a multiple file drag it will now show the reject styles/class and add any extra files to the rejected files.

**Comment by okonet** [comment]
Thanks for clarification. I think note is enough since we aren't breaking the API.
